In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder 
import sklearn
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from ThyroidDataProcess import data_processing, get_Xy
from sklearn.preprocessing import OneHotEncoder

In [4]:
train_df_ave_path = 'fillna_training_average.json'

In [5]:
df = data_processing("allhypo.test.txt", train_df_ave_path)

In [6]:
feature_cat = [ 'sex', 'on thyroxine', 'query on thyroxine','on antithyroid medication', 'sick',
               'pregnant', 'thyroid surgery','I131 treatment', 'query hypothyroid', 
               'query hyperthyroid', 'lithium', 'goitre', 'tumor', 'hypopituitary', 'psych', 
               'TSH measured', 'T3 measured', 'TT4 measured', 'T4U measured', 'FTI measured', 'referral source',]

In [7]:
feature_num = ['age','TSH_ln','T3', 'TT4', 'T4U', 'FTI']

In [8]:
X_test, y_test = get_Xy(df, feature_cat, feature_num)

/home/jun3/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:325: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.n_values is not None and self.n_values != 'auto':
/home/jun3/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:331: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)]'.
  warnings.warn(msg, DeprecationWarning)


In [9]:
from xgboost import XGBClassifier

In [10]:
from sklearn.externals import joblib
xgb = joblib.load("XGBoost_model.pkl")

In [11]:
y_test_pred = xgb.predict(X_test)

In [12]:
print("Classification report on the test data\n\n", classification_report(y_test, y_test_pred))
print('Confusion_matrix\n\n', confusion_matrix(y_test, y_test_pred))

Classification report on the test data

               precision    recall  f1-score   support

           0       1.00      1.00      1.00       901
           1       0.97      0.94      0.95        31
           2       0.95      1.00      0.98        40

   micro avg       1.00      1.00      1.00       972
   macro avg       0.97      0.98      0.97       972
weighted avg       1.00      1.00      1.00       972

Confusion_matrix

 [[899   1   1]
 [  1  29   1]
 [  0   0  40]]
